-- MySQL Script generated by MySQL Workbench
-- Tue Nov  3 14:26:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema assign04
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assign04
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assign04` DEFAULT CHARACTER SET utf8 ;
USE `assign04` ;

-- -----------------------------------------------------
-- Table `assign04`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assign04`.`blog` (
  `blog_id` INT NOT NULL,
  `blog_details` VARCHAR(45) NULL,
  PRIMARY KEY (`blog_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assign04`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assign04`.`member` (
  `member_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `blog_id` INT NOT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `fk_members_blogs1_idx` (`blog_id` ASC) VISIBLE,
  CONSTRAINT `fk_members_blogs1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `assign04`.`blog` (`blog_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assign04`.`member_registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assign04`.`member_registration` (
  `member_id` INT NOT NULL,
  `user_name` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  `acceptance` TINYINT NULL,
  `email_address` VARCHAR(45) NULL,
  INDEX `fk_member_registration_member1_idx` (`member_id` ASC) VISIBLE,
  PRIMARY KEY (`member_id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  CONSTRAINT `fk_member_registration_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `assign04`.`member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assign04`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assign04`.`contacts` (
  `contact_id` INT NOT NULL,
  `email_address` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  `website` VARCHAR(45) NULL,
  `members_member_id` INT NOT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `fk_contacts_members1_idx` (`members_member_id` ASC) VISIBLE,
  CONSTRAINT `fk_contacts_members1`
    FOREIGN KEY (`members_member_id`)
    REFERENCES `assign04`.`member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assign04`.`member_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assign04`.`member_history` (
  `contact_start` VARCHAR(45) NULL,
  `contact_end` VARCHAR(45) NULL,
  `member_id` INT NOT NULL,
  INDEX `fk_member_history_members_idx` (`member_id` ASC) VISIBLE,
  PRIMARY KEY (`member_id`),
  CONSTRAINT `fk_member_history_members`
    FOREIGN KEY (`member_id`)
    REFERENCES `assign04`.`member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assign04`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assign04`.`events` (
  `event_id` INT NOT NULL,
  `event_name` VARCHAR(45) NULL,
  `event_datetime` DATETIME NULL,
  `other_details` VARCHAR(255) NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assign04`.`blog_entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assign04`.`blog_entries` (
  `entry_id` INT NOT NULL,
  `blog_id` INT NOT NULL,
  PRIMARY KEY (`entry_id`),
  INDEX `fk_blog_entries_blogs1_idx` (`blog_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_entries_blogs1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `assign04`.`blog` (`blog_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
